name: 'Pintsizedrobotninja '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2319149
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#1d1b25'
    - '#7e767c'
    - '#57384c'
    - '#b1b08c'
  brandStrength: 1
  lightness: 0
  saturation: 0.1574468
  rhythmicContrast: 0.5042553
purpose: []
